name: Release Please

on:
  push:
    branches:
      - main

permissions: write-all

jobs:
  release-please:
    runs-on: ubuntu-latest
    outputs:
      releases_created: ${{ steps.release.outputs.releases_created }}
    steps:
      - uses: googleapis/release-please@v4
        id: release
