name: Test

on:
  push:
    branches: [main]
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Build caching
        uses: actions/cache@v4
        with:
          path: |
            ${{ github.workspace }}/.next/cache
          key: ${{ runner.os }}-nextjs-${{ hashFiles('**/yarn.lock') }}-${{ hashFiles('**/*.js', '**/*.jsx', '**/*.ts', '**/*.tsx') }}
          restore-keys: |
            ${{ runner.os }}-nextjs-${{ hashFiles('**/yarn.lock') }}-
      - name: Corepack enable
        run: corepack enable
      - name: Use Node.js
        uses: actions/setup-node@v5
        with:
          node-version: 22.x
          cache: 'yarn'
      - name: Install node_modules
        run: yarn install --immutable
      - name: Build
        run: yarn build
      - name: Test
        run: yarn test run
      - name: Format check
        run: yarn format:check
