name: Test

on:
  push:
    branches: [main]
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Corepack enable
        run: corepack enable
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18.x
          cache: 'yarn'
      - name: Install node_modules
        run: yarn install
      - name: Build
        run: yarn build

  test:
    runs-on: ubuntu-latest
    env:
      TZ: Asia/Tokyo
    steps:
      - uses: actions/checkout@v4
      - name: Corepack enable
        run: corepack enable
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18.x
          cache: 'yarn'
      - name: Install node_modules
        run: yarn install
      - name: Test
        run: yarn test run --coverage

  # ステータスチェック用
  test-status:
    needs: [build, test]
    # スキップ、成功の場合はステータスチェックをパスさせる
    if: ${{ always() }}
    runs-on: ubuntu-latest
    steps:
      - name: Check status
        run: |
          if [ '${{ contains(needs.*.result, 'failure') }}' = 'true' ]; then
            echo 'Failed some tests.'
            exit 1
          else
            echo 'Passed all tests.'
          fi
